name: Publish to NPM registry

on:
  release:
    types:
      - "published"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build sources
        run: npm run build
      - name: Publish to registry
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}